spring:
    datasource:
        platform: mysql
        url: jdbc:mysql://mysqldb:3306/biblioteka
        username: root
        password: lukasz123
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
        show-sql: true
